openapi: 3.0.0
info:
  title: Train Management API
  description: API documentation for Train Management System
  version: 1.0.0
servers:
  - url: http://localhost:8800/api-docs

paths:
  /auth/login:
    post:
      summary: User Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Successfully logged in
        '401':
          description: Unauthorized

  /auth/register:
    post:
      summary: User Registration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - firstname
                - username
                - email
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request

  /train/add:
    post:
      summary: Add a new train
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trainName:
                  type: string
                routeName:
                  type: string
              required:
                - trainName
                - routeName
      responses:
        '201':
          description: Train added successfully
        '400':
          description: Bad request

  /train/get-trains:
    get:
      summary: Get all trains
      responses:
        '200':
          description: A list of trains
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    trainName:
                      type: string
                    routeName:
                      type: string

  /train/get-train/{id}:
    get:
      summary: Get train by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The train ID
      responses:
        '200':
          description: Train details
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainName:
                    type: string
                  routeName:
                    type: string
        '404':
          description: Train not found

  /train-history:
    get:
      summary: Get train history by date
      parameters:
        - in: query
          name: date
          required: true
          schema:
            type: string
            format: date-time
          description: The date to get the train history for
      responses:
        '200':
          description: Train history data
          content:
            application/json:
              schema:
                type: object
        '404':
          description: Train history not found

  /train/get-train/{trainId}:
    get:
      summary: Get train by train ID
      parameters:
        - in: path
          name: trainId
          required: true
          schema:
            type: string
          description: The train ID
      responses:
        '200':
          description: Train details
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainName:
                    type: string
                  routeName:
                    type: string
        '404':
          description: Train not found

  /train/update-train/{id}:
    put:
      summary: Update train details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The train ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                trainName:
                  type: string
      responses:
        '200':
          description: Train updated successfully
        '400':
          description: Bad request
        '404':
          description: Train not found

  /train/remove/{id}:
    delete:
      summary: Remove a train
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The train ID
      responses:
        '200':
          description: Train removed successfully
        '404':
          description: Train not found

  /users/get-users:
    get:
      summary: Get all users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    firstname:
                      type: string
                    username:
                      type: string
                    email:
                      type: string

  /users/get-user/{id}:
    get:
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        '200':
          description: User details
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstname:
                    type: string
                  username:
                    type: string
                  email:
                    type: string
        '404':
          description: User not found

  /users/update-user/{id}:
    put:
      summary: Update user details
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstname:
                  type: string
      responses:
        '200':
          description: User updated successfully
        '400':
          description: Bad request
        '404':
          description: User not found

  /users/remove/{id}:
    delete:
      summary: Remove a user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The user ID
      responses:
        '200':
          description: User removed successfully
        '404':
          description: User not found
